
0: 384x640 (no detections), 608.6ms
Speed: 0.0ms preprocess, 608.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 583.2ms
Speed: 0.0ms preprocess, 583.2ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bien-so, 579.5ms
Speed: 0.0ms preprocess, 579.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[2024/03/19 12:30:56] ppocr WARNING: Since the angle classifier is not initialized, it will not be used during the forward process
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "d:\App_VN\tkCamera.py", line 53, in update_frame
    width = self.canvas.winfo_width()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1356, in winfo_width
    self.tk.call('winfo', 'width', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: can't invoke "winfo" command: application has been destroyed
